services:
  - type: web
    name: n8n-service
    env: docker
    plan: free
    autoDeploy: true

  - type: worker
    name: n8n-worker
    env: docker
    plan: free
    autoDeploy: true

databases:
  - name: n8n-db
    plan: free
    postgresMajorVersion: 14
